version: '3.1'
services:
  rabbitmq-master:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq-master
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - './docker/rabbitmq:/var/lib/rabbitmq'
    networks:
      - example_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  worker-lanca-foguete:
    image: php:8.2-cli
    hostname: worker-lanca-foguete
    restart: unless-stopped
    command: php /application/src/Workers/LancaFoguete.php # Comando para iniciar o worker
    volumes:
      - './:/application' # Mapeie o código-fonte para o contêiner
    networks:
      - example_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

networks:
  example_network:
    driver: bridge